version: '3'

services:
  rsyslog1:
    image: rsyslog-image
    volumes:
      - ./rsyslog1:/var/log/rsyslog    

  rsyslog2:
    image: rsyslog-image
    volumes:
      - ./rsyslog2:/var/log/rsyslog     

  load_balancer:
    image: nginx:latest
    ports:
      - 514:514
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
